# action.yml
name: 'run-test'
description: 'runs the test as given at the cli'
inputs:
  testFolder:
    required: true
runs:
  using: 'docker'
  image: 'docker/Dockerfile'
  args:
    - bash bin/runTest.sh ${{ inputs.testFolder }}
