on: [push]

jobs:
  run_withQ:
    runs-on: ubuntu-latest
    name: withQ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build-the-image
        id: run-with-Q
        uses: ./
        with:
          testFolder: 'source_withQ'
