on: [push]

jobs:
  run_withQ:
    runs-on: ubuntu-latest
    name: withQ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run-in-the-image
        id: run-with-Q
        uses: ./
        with:
          testFolder: 'source_withQ'
  run_withoutQ:
    runs-on: ubuntu-latest
    name: withoutQ
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run-in-the-image
        id: run-without-Q
        uses: ./
        with:
          testFolder: 'source_withoutQ'
